const ResumePreview = ({ data }) => {
  if (!data) return null;
  const { user, profile, skills, learning, achievements } = data;

  return (
    <div
      id="resume-print"
      className="bg-white text-slate-900 p-8 max-w-[210mm] mx-auto shadow-lg rounded-lg print:shadow-none print:rounded-none"
    >
      <header className="border-b-2 border-brand-500 pb-4 mb-6">
        <h1 className="text-3xl font-bold text-brand-800">{user?.name}</h1>
        {profile?.headline && (
          <p className="text-lg text-slate-600 mt-1">{profile.headline}</p>
        )}
        <p className="text-sm text-slate-500 mt-2">
          {[user?.email, user?.phone, profile?.location].filter(Boolean).join(" · ")}
        </p>
        <p className="text-sm text-brand-600 mt-1">
          {[profile?.github, profile?.linkedin, profile?.portfolio]
            .filter(Boolean)
            .join(" · ")}
        </p>
      </header>

      {profile?.summary && (
        <section className="mb-6">
          <h2 className="text-sm font-bold uppercase tracking-wide text-brand-700 mb-2">
            Summary
          </h2>
          <p className="text-sm leading-relaxed">{profile.summary}</p>
        </section>
      )}

      {skills?.length > 0 && (
        <section className="mb-6">
          <h2 className="text-sm font-bold uppercase tracking-wide text-brand-700 mb-2">
            Skills
          </h2>
          <p className="text-sm">{skills.join(" · ")}</p>
        </section>
      )}

      {learning?.length > 0 && (
        <section className="mb-6">
          <h2 className="text-sm font-bold uppercase tracking-wide text-brand-700 mb-2">
            IndLearn — Courses & progress
          </h2>
          <ul className="space-y-3 text-sm">
            {learning.map((item, i) => (
              <li key={i}>
                <p className="font-semibold">
                  {item.course} {item.batch && `(${item.batch})`}
                </p>
                <p className="text-slate-600">Progress: {item.progress}% complete</p>
                {item.milestones?.length > 0 && (
                  <p className="text-slate-500 text-xs mt-1">
                    {item.milestones.join(" · ")}
                  </p>
                )}
              </li>
            ))}
          </ul>
        </section>
      )}

      {achievements?.length > 0 && (
        <section className="mb-6">
          <h2 className="text-sm font-bold uppercase tracking-wide text-brand-700 mb-2">
            Learning achievements
          </h2>
          <ul className="list-disc list-inside text-sm text-slate-700">
            {[...new Set(achievements)].map((a) => (
              <li key={a}>{a}</li>
            ))}
          </ul>
        </section>
      )}

      {profile?.education?.length > 0 && profile.education[0]?.school && (
        <section className="mb-6">
          <h2 className="text-sm font-bold uppercase tracking-wide text-brand-700 mb-2">
            Education
          </h2>
          {profile.education.map((edu, i) => (
            <div key={i} className="text-sm mb-2">
              <p className="font-semibold">
                {edu.degree} — {edu.school}
              </p>
              {edu.year && <p className="text-slate-500">{edu.year}</p>}
            </div>
          ))}
        </section>
      )}

      {profile?.experience?.length > 0 && profile.experience[0]?.company && (
        <section>
          <h2 className="text-sm font-bold uppercase tracking-wide text-brand-700 mb-2">
            Experience
          </h2>
          {profile.experience.map((exp, i) => (
            <div key={i} className="text-sm mb-3">
              <p className="font-semibold">
                {exp.role} at {exp.company}
              </p>
              {(exp.start || exp.end) && (
                <p className="text-slate-500 text-xs">
                  {exp.start} – {exp.end || "Present"}
                </p>
              )}
              {exp.description && <p className="mt-1">{exp.description}</p>}
            </div>
          ))}
        </section>
      )}

      <p className="text-xs text-slate-400 mt-8 pt-4 border-t">
        Generated by IndLearn · {new Date(data.generatedAt || Date.now()).toLocaleDateString()}
      </p>
    </div>
  );
};

export default ResumePreview;
